// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: data/rpcmessage.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCMessageServiceClient is the client API for RPCMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCMessageServiceClient interface {
	Insert(ctx context.Context, in *RPCMessageRequest, opts ...grpc.CallOption) (*RPCMessageResponse, error)
}

type rPCMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCMessageServiceClient(cc grpc.ClientConnInterface) RPCMessageServiceClient {
	return &rPCMessageServiceClient{cc}
}

func (c *rPCMessageServiceClient) Insert(ctx context.Context, in *RPCMessageRequest, opts ...grpc.CallOption) (*RPCMessageResponse, error) {
	out := new(RPCMessageResponse)
	err := c.cc.Invoke(ctx, "/api.v1.RPCMessageService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCMessageServiceServer is the server API for RPCMessageService service.
// All implementations must embed UnimplementedRPCMessageServiceServer
// for forward compatibility
type RPCMessageServiceServer interface {
	Insert(context.Context, *RPCMessageRequest) (*RPCMessageResponse, error)
	mustEmbedUnimplementedRPCMessageServiceServer()
}

// UnimplementedRPCMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRPCMessageServiceServer struct {
}

func (UnimplementedRPCMessageServiceServer) Insert(context.Context, *RPCMessageRequest) (*RPCMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedRPCMessageServiceServer) mustEmbedUnimplementedRPCMessageServiceServer() {}

// UnsafeRPCMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCMessageServiceServer will
// result in compilation errors.
type UnsafeRPCMessageServiceServer interface {
	mustEmbedUnimplementedRPCMessageServiceServer()
}

func RegisterRPCMessageServiceServer(s grpc.ServiceRegistrar, srv RPCMessageServiceServer) {
	s.RegisterService(&RPCMessageService_ServiceDesc, srv)
}

func _RPCMessageService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMessageServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.RPCMessageService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMessageServiceServer).Insert(ctx, req.(*RPCMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCMessageService_ServiceDesc is the grpc.ServiceDesc for RPCMessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCMessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.RPCMessageService",
	HandlerType: (*RPCMessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _RPCMessageService_Insert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data/rpcmessage.proto",
}
